[package]
name = "udmp-parser"
version = "0.3.0"
edition = "2024"
authors = ["Axel '0vercl0k' Souchet"]
categories = ["parser-implementations"]
description = "A Rust crate for parsing Windows user minidumps"
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/src/**",
    "/examples/**",
    "README.md",
]
keywords = ["windows", "minidump", "crashdump"]
license = "MIT"
repository = "https://github.com/0vercl0k/udmp-parser-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[example]]
name = "parser"
[profile.release]
panic = "abort"
