name: Builds

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: fmt
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up rust
        run: rustup default stable

      - name: cargo fmt
        run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up rust
        run: rustup default stable

      - name: cargo clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo clippy --example parser

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up rust
        run: rustup default stable

      - name: cargo doc
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        run: cargo doc

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: build & test / ${{ matrix.os }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up rust
        run: rustup default stable

      - name: cargo test
        run: cargo test

      - name: cargo build
        run: cargo build --release --example parser

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: parser-${{ matrix.os }}
          path: |
            target/release/examples/parser.exe
            target/release/examples/parser.pdb
            target/release/examples/parser
